import Head from 'next/head'

type Props = {
    title: string,
    description?: string
}

 export default function Layout(props: Props) {
    return (
        <Head>
            <title>{props.title}</title>
            <meta name={props.description} content='Generated by create next app' />
            <link rel='icon' href='/favicon.ico' />
        </Head>
    )
}